### ISSUE TITLE
タスク管理テーブルを作成する

### ISSUE THREAD

**Issue by yus33** [koiwas/ShibaStars#3]
## 概要
- タスク管理テーブルを作成する

## テーブル定義

users

| カラム名 | 論理名 | データ型 | キー | 備考 |
| ---- | ---- | ---- | ---- | ---- |
| id | id | int |  |
| username | 名前 | varchar | UNI | |
| created_by | 作成者 | varchar | | 初期登録時のデフォ値は`system`など |
| created_at | 作成日 | datetime | | |
| updated_by | 更新者 | datetime | | 初期登録時のデフォ値は`system`など |
| updated_at | 更新日 | datetime | | | |
| deleted_by | 削除者 | varchar | | | |
| deleted_at | 削除日 | datetime | | | |

tasks

| カラム名 | 論理名 | データ型 | キー | 備考 |
| ---- | ---- | ---- | ---- | ---- |
| id | id | int | | |
| is_closed | 終了済みフラグ | bool | | |
| created_by | 作成者 | varchar | | |
| created_at | 作成日 | datetime | | |
| updated_by | 更新者 | varchar | | |
| updated_at | 更新日 | datetime | | |
| deleted_by | 削除者 | varchar | | |
| deleted_at | 削除日 | datetime | | |

contents
| カラム名 | 論理名 | データ型 | キー | 備考 |
| ---- | ---- | ---- | ---- | ---- |
| id | id | int | | |
| task_id | tasksのid | int | MUL | |
| content | 内容 | varchar | | |
| is_checked | チェック済みフラグ | bool | | |
| created_by | 作成者 | varchar | | |
| created_at | 作成日 | datetime | | |
| updated_by | 更新者 | varchar | | |
| updated_at | 更新日 | datetime | | |
| deleted_by | 削除者 | varchar | | |
| deleted_at | 削除日 | datetime | | |

- 参考
https://qiita.com/TetsujinUgatsu/items/116aba1ad2303b475180

**Comment by koiwas** [comment]
Merge済みのためクローズします。
